name: "💡 Предложение / Идея"
description: "Предложите новую функцию или улучшение для модпака"
title: "[Предложение]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Есть идея? Отлично! Пожалуйста, заполните форму ниже.
  - type: input
    id: modpack-version
    attributes:
      label: "Версия модпака"
      description: "Какую версию PyroCraft вы используете?"
      placeholder: "v0.0.20"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Ваше предложение"
      description: "Опишите вашу идею подробно. Что бы вы хотели добавить или изменить?"
      placeholder: "Я думаю, стоит добавить мод X, потому что..."
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "Зачем?"
      description: "Объясните, почему это улучшение будет полезно."
      placeholder: "Это повысит производительность / баланс / креативность..."
