name: "💡 Suggestion / Feature Request"
description: "Suggest a new feature or improvement for the modpack"
title: "[Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it! Please fill out the form below.
  - type: input
    id: modpack-version
    attributes:
      label: "Modpack Version"
      description: "Which version of PyroCraft are you using?"
      placeholder: "v0.0.20"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Your Suggestion"
      description: "Describe your idea clearly. What do you want to see added or improved?"
      placeholder: "I think adding mod X would help because..."
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "Why?"
      description: "Explain why this change would improve the pack."
      placeholder: "It would improve performance / balance / creativity..."
